gitlab: Restore timeout for webservice
Vcsrepo[/usr/src/linux]: change from 'absent' to 'latest' failed:
Execution of '/usr/sbin/git clone https://gitlab.joyfullee.me/nest/forks/linux.git /usr/src/linux' returned 128:
Cloning into '/usr/src/linux'...
error: RPC failed; HTTP 504 curl 22 The requested URL returned error: 504
fatal: expected 'packfile'